In [3]:
import pandas as pd
import math
# librerías


# datos
datos1 = [78.5,74.3,104.3,87.6,95.9,109.2,102.7,72.5,93.1,115.9,83.8,113.3,109.4]
datos2 = [7,1,11,11,7,11,3,1,2,21,1,11,10]
datos3 = [26,29,56,31,52,55,71,31,54,47,40,66,68]
datos4 = [6,15,8,8,6,9,17,22,18,4,23,9,8]
datos5 = [60,52,20,47,33,22,6,44,22,26,34,12,12]

# diccionario
diccionario = {"y":datos1,
               "x1":datos2,
               "x2":datos3,
               "x3":datos4,
               "x4":datos5,}

#tabla
df= pd.DataFrame(diccionario)
df



,y,x1,x2,x3,x4
0,78.5,7,26,6,60
1,74.3,1,29,15,52
2,104.3,11,56,8,20
3,87.6,11,31,8,47
4,95.9,7,52,6,33
5,109.2,11,55,9,22
6,102.7,3,71,17,6
7,72.5,1,31,22,44
8,93.1,2,54,18,22
9,115.9,21,47,4,26


In [ ]:
# Replace the 'y' column with ones
df_modified = df.copy()
df_modified['y'] = 1

# Convert the modified DataFrame to a NumPy matrix
matrix_with_y_as_ones = df_modified.values

# Display the resulting matrix
print(matrix_with_y_as_ones)

[[ 1  7 26  6 60]
 [ 1  1 29 15 52]
 [ 1 11 56  8 20]
 [ 1 11 31  8 47]
 [ 1  7 52  6 33]
 [ 1 11 55  9 22]
 [ 1  3 71 17  6]
 [ 1  1 31 22 44]
 [ 1  2 54 18 22]
 [ 1 21 47  4 26]
 [ 1  1 40 23 34]
 [ 1 11 66  9 12]
 [ 1 10 68  8 12]]


In [ ]:
# Transpose the matrix
transposed_matrix = matrix_with_y_as_ones.T

# Display the transposed matrix
print(transposed_matrix)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 7  1 11 11  7 11  3  1  2 21  1 11 10]
 [26 29 56 31 52 55 71 31 54 47 40 66 68]
 [ 6 15  8  8  6  9 17 22 18  4 23  9  8]
 [60 52 20 47 33 22  6 44 22 26 34 12 12]]


In [ ]:
import numpy as np

# Extract the 'y' column as a NumPy array
y_column_vector = df['y'].values.reshape(-1, 1)

# Display the column vector
print(y_column_vector)

[[ 78.5]
 [ 74.3]
 [104.3]
 [ 87.6]
 [ 95.9]
 [109.2]
 [102.7]
 [ 72.5]
 [ 93.1]
 [115.9]
 [ 83.8]
 [113.3]
 [109.4]]


In [ ]:
import numpy as np

# Multiply the transposed matrix by the original matrix
result_matrix = np.dot(transposed_matrix, matrix_with_y_as_ones)

# Display the resulting matrix
print(result_matrix)

[[   13    97   626   153   390]
 [   97  1139  4922   769  2620]
 [  626  4922 33050  7201 15739]
 [  153   769  7201  2293  4628]
 [  390  2620 15739  4628 15062]]


In [ ]:
import numpy as np

# Calculate the inverse of the result_matrix
inverse_result_matrix = np.linalg.inv(result_matrix)

# Display the inverse matrix
print(inverse_result_matrix)

[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]


In [ ]:
import numpy as np

# Multiply inverse_result_matrix by transposed_matrix
step1_multiplication = np.dot(inverse_result_matrix, transposed_matrix)

# Multiply the result by y_column_vector
final_result_beta = np.dot(step1_multiplication, y_column_vector)

# Display the final result (which should be the beta coefficients)
print(final_result_beta)

[[62.4053693 ]
 [ 1.55110265]
 [ 0.51016758]
 [ 0.1019094 ]
 [-0.14406103]]
